/**
 * Canonical list of effectus.com.hr pages to index — Croatian content only.
 * NOTE: Effectus uses flat URLs (no /studiji/ subdirectory)
 * Grouped by entity_type for proper metadata tagging.
 *
 * Updated: auto-discovered via WP REST API (/wp/v2/pages)
 * Total: ~320 URLs (48 original + 90 nastavnici + 158 predmeti + ostalo)
 */

export const PAGES = [

  // ─── HOMEPAGE & O NAMA ────────────────────────────────────────────────────
  { url: 'https://effectus.com.hr',                                            entity_type: 'opcenito', entity_name: 'EFFECTUS veleučilište' },
  { url: 'https://effectus.com.hr/upoznaj-nas',                                entity_type: 'opcenito', entity_name: 'Upoznaj Effectus' },
  { url: 'https://effectus.com.hr/misija-i-vizija',                            entity_type: 'opcenito', entity_name: 'Misija i vizija' },
  { url: 'https://effectus.com.hr/organizacijska-struktura',                   entity_type: 'opcenito', entity_name: 'Organizacijska struktura' },
  { url: 'https://effectus.com.hr/voditelji-studija',                          entity_type: 'opcenito', entity_name: 'Voditelji studija' },
  { url: 'https://effectus.com.hr/voditelji-studijskih-grupa',                 entity_type: 'opcenito', entity_name: 'Voditelji studijskih grupa' },
  { url: 'https://effectus.com.hr/savjet-effectusa',                           entity_type: 'opcenito', entity_name: 'Savjet Effectusa' },
  { url: 'https://effectus.com.hr/strategije',                                 entity_type: 'opcenito', entity_name: 'Strategije' },
  { url: 'https://effectus.com.hr/etika',                                      entity_type: 'opcenito', entity_name: 'Etika' },
  { url: 'https://effectus.com.hr/akti-ustanove',                              entity_type: 'opcenito', entity_name: 'Akti ustanove' },
  { url: 'https://effectus.com.hr/uprava',                                     entity_type: 'opcenito', entity_name: 'Uprava' },
  { url: 'https://effectus.com.hr/dekan',                                      entity_type: 'opcenito', entity_name: 'Dekan' },
  { url: 'https://effectus.com.hr/prodekani',                                  entity_type: 'opcenito', entity_name: 'Prodekani' },
  { url: 'https://effectus.com.hr/vijece-veleucilista',                        entity_type: 'opcenito', entity_name: 'Vijeće veleučilišta' },
  { url: 'https://effectus.com.hr/upravno-vijece',                             entity_type: 'opcenito', entity_name: 'Upravno vijeće' },
  { url: 'https://effectus.com.hr/odjeli',                                     entity_type: 'opcenito', entity_name: 'Odjeli' },
  { url: 'https://effectus.com.hr/katedre',                                    entity_type: 'opcenito', entity_name: 'Katedre' },
  { url: 'https://effectus.com.hr/centri',                                     entity_type: 'opcenito', entity_name: 'Centri' },
  { url: 'https://effectus.com.hr/tajnistvo',                                  entity_type: 'opcenito', entity_name: 'Tajništvo' },
  { url: 'https://effectus.com.hr/kvaliteta',                                  entity_type: 'opcenito', entity_name: 'Kvaliteta' },
  { url: 'https://effectus.com.hr/odbor-za-kvalitetu',                         entity_type: 'opcenito', entity_name: 'Odbor za kvalitetu' },
  { url: 'https://effectus.com.hr/pravo-na-informacije',                       entity_type: 'opcenito', entity_name: 'Pravo na informacije' },

  // ─── UPISI ────────────────────────────────────────────────────────────────
  { url: 'https://effectus.com.hr/otvoreni-upisi',                             entity_type: 'upisi', entity_name: 'Otvoreni upisi' },
  { url: 'https://effectus.com.hr/postupak-upisa-2',                           entity_type: 'upisi', entity_name: 'Postupak upisa' },
  { url: 'https://effectus.com.hr/cijena-skolarine',                           entity_type: 'upisi', entity_name: 'Cijena školarine' },
  { url: 'https://effectus.com.hr/skolarina',                                  entity_type: 'upisi', entity_name: 'Školarina' },
  { url: 'https://effectus.com.hr/prijemni-ispit',                             entity_type: 'upisi', entity_name: 'Prijemni ispit' },
  { url: 'https://effectus.com.hr/upis-prijelazom-s-drugog-studija',           entity_type: 'upisi', entity_name: 'Upis prijelazom s drugog studija' },
  { url: 'https://effectus.com.hr/ranjive-i-podzastupljene-skupine-studenata', entity_type: 'upisi', entity_name: 'Ranjive i podzastupljene skupine' },

  // ─── STUDIJSKI PROGRAMI — PRIJEDIPLOMSKI ─────────────────────────────────
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo',                 entity_type: 'studij', entity_name: 'Financije i poslovno pravo' },
  { url: 'https://effectus.com.hr/pravo',                                      entity_type: 'studij', entity_name: 'Pravo' },
  { url: 'https://effectus.com.hr/poslovna-ekonomija',                         entity_type: 'studij', entity_name: 'Poslovna ekonomija' },
  { url: 'https://effectus.com.hr/poduzetnistvo-2',                            entity_type: 'studij', entity_name: 'Poduzetništvo' },
  { url: 'https://effectus.com.hr/ishodi-ucenja-studijskog-programa',          entity_type: 'studij', entity_name: 'Ishodi učenja studijskog programa' },
  { url: 'https://effectus.com.hr/ishodi-ucenja-studijskog-programa-2',        entity_type: 'studij', entity_name: 'Ishodi učenja studijskog programa 2' },
  { url: 'https://effectus.com.hr/ishodi-ucenja-studijskog-programa-3',        entity_type: 'studij', entity_name: 'Ishodi učenja studijskog programa 3' },

  // ─── STUDIJSKI PROGRAMI — DIPLOMSKI ───────────────────────────────────────
  { url: 'https://effectus.com.hr/diplomski-studiji',                          entity_type: 'studij', entity_name: 'Diplomski studiji' },
  { url: 'https://effectus.com.hr/menadzment-financija',                       entity_type: 'studij', entity_name: 'Menadžment financija' },
  { url: 'https://effectus.com.hr/menadzment-u-zdravstvu',                     entity_type: 'studij', entity_name: 'Menadžment u zdravstvu' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja',   entity_type: 'studij', entity_name: 'Menadžment ljudskih potencijala i znanja' },
  { url: 'https://effectus.com.hr/analiticki-menadzment',                      entity_type: 'studij', entity_name: 'Analitički menadžment' },
  { url: 'https://effectus.com.hr/bihevioralna-ekonomija',                     entity_type: 'studij', entity_name: 'Bihevioralna ekonomija' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo',                    entity_type: 'studij', entity_name: 'Porezi i poslovno pravo' },
  { url: 'https://effectus.com.hr/pravo-i-management-nekretnina',              entity_type: 'studij', entity_name: 'Pravo i management nekretnina' },

  // ─── NASTAVNICI — LISTA ───────────────────────────────────────────────────
  { url: 'https://effectus.com.hr/nastavnici-i-suradnici',                     entity_type: 'nastavnik', entity_name: 'Nastavnici i suradnici' },
  { url: 'https://effectus.com.hr/predavaci',                                  entity_type: 'nastavnik', entity_name: 'Predavači' },

  // ─── NASTAVNICI — INDIVIDUALNI PROFILI ───────────────────────────────────
  { url: 'https://effectus.com.hr/roman-domovic',                              entity_type: 'nastavnik', entity_name: 'Roman Domović' },
  { url: 'https://effectus.com.hr/danijela-pongrac',                           entity_type: 'nastavnik', entity_name: 'Danijela Pongrac' },
  { url: 'https://effectus.com.hr/vjeran-malenica-dipl-iur',                   entity_type: 'nastavnik', entity_name: 'Vjeran Malenica' },
  { url: 'https://effectus.com.hr/ivana-vitovski-dipl-oec',                    entity_type: 'nastavnik', entity_name: 'Ivana Vitovski' },
  { url: 'https://effectus.com.hr/nikolina-bacurin-dipl-oec',                  entity_type: 'nastavnik', entity_name: 'Nikolina Bačurin' },
  { url: 'https://effectus.com.hr/sinisa-urosev-mag-math',                     entity_type: 'nastavnik', entity_name: 'Siniša Urošev' },
  { url: 'https://effectus.com.hr/ivona-javorovic-mag-oec',                    entity_type: 'nastavnik', entity_name: 'Ivona Javorović' },
  { url: 'https://effectus.com.hr/danijel-lukovic-mr-spec-oec',                entity_type: 'nastavnik', entity_name: 'Danijel Luković' },
  { url: 'https://effectus.com.hr/iris-kulik-bokun-mag-philol-angl-et-germ',   entity_type: 'nastavnik', entity_name: 'Iris Kulik Bokun' },
  { url: 'https://effectus.com.hr/darija-ivandic-vidovic',                     entity_type: 'nastavnik', entity_name: 'Darija Ivandić Vidović' },
  { url: 'https://effectus.com.hr/helena-popovic-petrusic',                    entity_type: 'nastavnik', entity_name: 'Helena Popović Petrušić' },
  { url: 'https://effectus.com.hr/vjeran-buselic',                             entity_type: 'nastavnik', entity_name: 'Vjeran Bušelić' },
  { url: 'https://effectus.com.hr/tihana-barlek',                              entity_type: 'nastavnik', entity_name: 'Tihana Barlek' },
  { url: 'https://effectus.com.hr/lucia-belovic',                              entity_type: 'nastavnik', entity_name: 'Lucia Belović' },
  { url: 'https://effectus.com.hr/borna-herceg',                               entity_type: 'nastavnik', entity_name: 'Borna Herceg' },
  { url: 'https://effectus.com.hr/petra-filipcic',                             entity_type: 'nastavnik', entity_name: 'Petra Filipčić' },
  { url: 'https://effectus.com.hr/ivan-zilic',                                 entity_type: 'nastavnik', entity_name: 'Ivan Žilić' },
  { url: 'https://effectus.com.hr/dr-sc-ivan-zilic',                           entity_type: 'nastavnik', entity_name: 'Ivan Žilić (dr. sc.)' },
  { url: 'https://effectus.com.hr/srecko-zajec',                               entity_type: 'nastavnik', entity_name: 'Srećko Zajec' },
  { url: 'https://effectus.com.hr/tamara-nemeth',                              entity_type: 'nastavnik', entity_name: 'Tamara Nemeth' },
  { url: 'https://effectus.com.hr/jasminka-lulic-stipetic',                    entity_type: 'nastavnik', entity_name: 'Jasminka Lulić Stipetić' },
  { url: 'https://effectus.com.hr/anita-lulic',                                entity_type: 'nastavnik', entity_name: 'Anita Lulić' },
  { url: 'https://effectus.com.hr/ivana-zupan',                                entity_type: 'nastavnik', entity_name: 'Ivana Župan' },
  { url: 'https://effectus.com.hr/jure-vucenovic',                             entity_type: 'nastavnik', entity_name: 'Jure Vučenović' },
  { url: 'https://effectus.com.hr/sicaja-zeljko-mag-nov',                      entity_type: 'nastavnik', entity_name: 'Željko Sičaja' },
  { url: 'https://effectus.com.hr/domagoj-poljak-str-spec-oec',                entity_type: 'nastavnik', entity_name: 'Domagoj Poljak' },
  { url: 'https://effectus.com.hr/tina-matic-mag-iur',                         entity_type: 'nastavnik', entity_name: 'Tina Matić' },
  { url: 'https://effectus.com.hr/zlatko-hodak',                               entity_type: 'nastavnik', entity_name: 'Zlatko Hodak' },
  { url: 'https://effectus.com.hr/hrvoje-patajac',                             entity_type: 'nastavnik', entity_name: 'Hrvoje Patajac' },
  { url: 'https://effectus.com.hr/ivana-rukavina',                             entity_type: 'nastavnik', entity_name: 'Ivana Rukavina' },
  { url: 'https://effectus.com.hr/nastavnici-i-suradnici/ana-uzelac',          entity_type: 'nastavnik', entity_name: 'Ana Uzelac' },
  { url: 'https://effectus.com.hr/nastavnici-i-suradnici/mirta-mandaric',      entity_type: 'nastavnik', entity_name: 'Mirta Mandarić' },
  { url: 'https://effectus.com.hr/maja-janach',                                entity_type: 'nastavnik', entity_name: 'Maja Janach' },
  { url: 'https://effectus.com.hr/nastavnici-i-suradnici/miroslav-grgurek',    entity_type: 'nastavnik', entity_name: 'Miroslav Grgurek' },
  { url: 'https://effectus.com.hr/ivan-galek',                                 entity_type: 'nastavnik', entity_name: 'Ivan Galek' },
  { url: 'https://effectus.com.hr/mladen-vedris',                              entity_type: 'nastavnik', entity_name: 'Mladen Vedriš' },
  { url: 'https://effectus.com.hr/josip-kunsabo',                              entity_type: 'nastavnik', entity_name: 'Josip Kunsabo' },
  { url: 'https://effectus.com.hr/petar-veic',                                 entity_type: 'nastavnik', entity_name: 'Petar Veić' },
  { url: 'https://effectus.com.hr/igor-miklousic',                             entity_type: 'nastavnik', entity_name: 'Igor Mikloušić' },
  { url: 'https://effectus.com.hr/anton-florijan-barisic',                     entity_type: 'nastavnik', entity_name: 'Anton Florijan Barišić' },
  { url: 'https://effectus.com.hr/ratka-jurkovic',                             entity_type: 'nastavnik', entity_name: 'Ratka Jurković' },
  { url: 'https://effectus.com.hr/mario-rasic',                                entity_type: 'nastavnik', entity_name: 'Mario Rašić' },
  { url: 'https://effectus.com.hr/mirko-talajic',                              entity_type: 'nastavnik', entity_name: 'Mirko Talajić' },
  { url: 'https://effectus.com.hr/dubravko-radosevic',                         entity_type: 'nastavnik', entity_name: 'Dubravko Radošević' },
  { url: 'https://effectus.com.hr/ante-orlovic',                               entity_type: 'nastavnik', entity_name: 'Ante Orlović' },
  { url: 'https://effectus.com.hr/doc-dr-dc-ante-orlovic',                     entity_type: 'nastavnik', entity_name: 'Ante Orlović (izv. prof. dr. sc.)' },
  { url: 'https://effectus.com.hr/darko-milkovic',                             entity_type: 'nastavnik', entity_name: 'Darko Milković' },
  { url: 'https://effectus.com.hr/tomislav-lucic',                             entity_type: 'nastavnik', entity_name: 'Tomislav Lucić' },
  { url: 'https://effectus.com.hr/dragutin-gutic',                             entity_type: 'nastavnik', entity_name: 'Dragutin Gutić' },
  { url: 'https://effectus.com.hr/ivan-curkovic',                              entity_type: 'nastavnik', entity_name: 'Ivan Ćurković' },
  { url: 'https://effectus.com.hr/vesna-cigan',                                entity_type: 'nastavnik', entity_name: 'Vesna Cigan' },
  { url: 'https://effectus.com.hr/tajana-barbic',                              entity_type: 'nastavnik', entity_name: 'Tajana Barbić' },
  { url: 'https://effectus.com.hr/pasko-anic-antic',                           entity_type: 'nastavnik', entity_name: 'Paško Anić Antić' },
  { url: 'https://effectus.com.hr/jelena-uzelac',                              entity_type: 'nastavnik', entity_name: 'Jelena Uzelac' },
  { url: 'https://effectus.com.hr/natalia-tutek',                              entity_type: 'nastavnik', entity_name: 'Natalia Tutek' },
  { url: 'https://effectus.com.hr/iva-tomic',                                  entity_type: 'nastavnik', entity_name: 'Iva Tomić' },
  { url: 'https://effectus.com.hr/bojan-tomic',                                entity_type: 'nastavnik', entity_name: 'Bojan Tomić' },
  { url: 'https://effectus.com.hr/aljosa-sestanovic',                          entity_type: 'nastavnik', entity_name: 'Aljoša Šestanović' },
  { url: 'https://effectus.com.hr/duska-sarin',                                entity_type: 'nastavnik', entity_name: 'Duška Šarin' },
  { url: 'https://effectus.com.hr/danko-sucevic',                              entity_type: 'nastavnik', entity_name: 'Danko Sučević' },
  { url: 'https://effectus.com.hr/milan-stipic',                               entity_type: 'nastavnik', entity_name: 'Milan Stipić' },
  { url: 'https://effectus.com.hr/ljiljana-skendrovic',                        entity_type: 'nastavnik', entity_name: 'Ljiljana Skendrović' },
  { url: 'https://effectus.com.hr/drazen-pavlic',                              entity_type: 'nastavnik', entity_name: 'Dražen Pavlić' },
  { url: 'https://effectus.com.hr/cedo-maletic',                               entity_type: 'nastavnik', entity_name: 'Čedo Maletić' },
  { url: 'https://effectus.com.hr/mirjana-mahovic-komljenovic',                entity_type: 'nastavnik', entity_name: 'Mirjana Mahović Komljenović' },
  { url: 'https://effectus.com.hr/gordana-letica',                             entity_type: 'nastavnik', entity_name: 'Gordana Letica' },
  { url: 'https://effectus.com.hr/mira-lenardic',                              entity_type: 'nastavnik', entity_name: 'Mira Lenardić' },
  { url: 'https://effectus.com.hr/jasna-kropf',                                entity_type: 'nastavnik', entity_name: 'Jasna Kropf' },
  { url: 'https://effectus.com.hr/darija-korkut',                              entity_type: 'nastavnik', entity_name: 'Darija Korkut' },
  { url: 'https://effectus.com.hr/marija-kalinic',                             entity_type: 'nastavnik', entity_name: 'Marija Kalinić' },
  { url: 'https://effectus.com.hr/visnja-juric',                               entity_type: 'nastavnik', entity_name: 'Višnja Jurić' },
  { url: 'https://effectus.com.hr/miljenko-javorovic',                         entity_type: 'nastavnik', entity_name: 'Miljenko Javorović' },
  { url: 'https://effectus.com.hr/marica-javorovic',                           entity_type: 'nastavnik', entity_name: 'Marica Javorović' },
  { url: 'https://effectus.com.hr/zdravka-jagic',                              entity_type: 'nastavnik', entity_name: 'Zdravka Jagić' },
  { url: 'https://effectus.com.hr/mladen-ilic',                                entity_type: 'nastavnik', entity_name: 'Mladen Ilić' },
  { url: 'https://effectus.com.hr/duro-horvat',                                entity_type: 'nastavnik', entity_name: 'Đuro Horvat' },
  { url: 'https://effectus.com.hr/goran-hanzek',                               entity_type: 'nastavnik', entity_name: 'Goran Hanžek' },
  { url: 'https://effectus.com.hr/sanja-gutic-martincic',                      entity_type: 'nastavnik', entity_name: 'Sanja Gutić Martinčić' },
  { url: 'https://effectus.com.hr/blazenka-deanovic',                          entity_type: 'nastavnik', entity_name: 'Blaženka Deanović' },
  { url: 'https://effectus.com.hr/vedran-ceranic',                             entity_type: 'nastavnik', entity_name: 'Vedran Ceranić' },
  { url: 'https://effectus.com.hr/mirjana-bautovic',                           entity_type: 'nastavnik', entity_name: 'Mirjana Bautović' },
  { url: 'https://effectus.com.hr/robert-kopal',                               entity_type: 'nastavnik', entity_name: 'Robert Kopal' },
  { url: 'https://effectus.com.hr/doc-dr-sc-maja-kolega',                      entity_type: 'nastavnik', entity_name: 'Maja Kolega' },
  { url: 'https://effectus.com.hr/dr-sc-tatjana-tos',                          entity_type: 'nastavnik', entity_name: 'Tajana Toš' },
  { url: 'https://effectus.com.hr/dr-sc-zeljka-zavisic',                       entity_type: 'nastavnik', entity_name: 'Željka Zavišić' },
  { url: 'https://effectus.com.hr/marija-milicevic-mag-iur',                   entity_type: 'nastavnik', entity_name: 'Marija Miličević' },
  { url: 'https://effectus.com.hr/dr-sc-nada-rajic-antic',                     entity_type: 'nastavnik', entity_name: 'Nada Rajić Antić' },
  { url: 'https://effectus.com.hr/petar-pierre-matek',                         entity_type: 'nastavnik', entity_name: 'Petar-Pierre Matek' },
  { url: 'https://effectus.com.hr/savjetnik-za-studente',                      entity_type: 'nastavnik', entity_name: 'Savjetnik za studente' },

  // ─── STUDENTSKE SLUŽBE ────────────────────────────────────────────────────
  { url: 'https://effectus.com.hr/sluzba-za-podrsku-studentima-i-nastavnicima', entity_type: 'opcenito', entity_name: 'Služba za podršku studentima i nastavnicima' },
  { url: 'https://effectus.com.hr/knjiznica',                                   entity_type: 'opcenito', entity_name: 'Knjižnica' },
  { url: 'https://effectus.com.hr/centar-karijera',                             entity_type: 'opcenito', entity_name: 'Centar karijera' },
  { url: 'https://effectus.com.hr/centar-savjetovanja',                         entity_type: 'opcenito', entity_name: 'Centar savjetovanja' },
  { url: 'https://effectus.com.hr/studentski-zbor',                             entity_type: 'opcenito', entity_name: 'Studentski zbor' },
  { url: 'https://effectus.com.hr/alumni',                                      entity_type: 'opcenito', entity_name: 'Alumni' },
  { url: 'https://effectus.com.hr/akademski-kalendar',                          entity_type: 'opcenito', entity_name: 'Akademski kalendar' },
  { url: 'https://effectus.com.hr/korisnicki-identiteti-u-ldap-imeniku',        entity_type: 'opcenito', entity_name: 'Korisnički identiteti (AAI)' },
  { url: 'https://effectus.com.hr/centar-izvrsnosti',                           entity_type: 'opcenito', entity_name: 'Centar izvrsnosti' },

  // ─── CJELOŽIVOTNO OBRAZOVANJE ─────────────────────────────────────────────
  { url: 'https://effectus.com.hr/cjelozivotno-obrazovanje',                    entity_type: 'cjelozivotni_program', entity_name: 'Cjeloživotno obrazovanje' },
  { url: 'https://effectus.com.hr/certifikati',                                 entity_type: 'cjelozivotni_program', entity_name: 'Certifikati' },
  { url: 'https://effectus.com.hr/mini-mba-doing-business-4-0-db4-executive',   entity_type: 'cjelozivotni_program', entity_name: 'Mini MBA — Executive' },
  { url: 'https://effectus.com.hr/mini-mba-doing-business-4-0-db4-management',  entity_type: 'cjelozivotni_program', entity_name: 'Mini MBA — Management' },
  { url: 'https://effectus.com.hr/mini-mba-doing-business-4-0-db4-operative',   entity_type: 'cjelozivotni_program', entity_name: 'Mini MBA — Operative' },
  { url: 'https://effectus.com.hr/drustveno-odgovorno-poslovanje',              entity_type: 'cjelozivotni_program', entity_name: 'Društveno odgovorno poslovanje' },
  { url: 'https://effectus.com.hr/porezni-a-specijalist-ica-2',                entity_type: 'cjelozivotni_program', entity_name: 'Porezni/a specijalist/ica' },
  { url: 'https://effectus.com.hr/voditelj-ica-nadzora-i-korporativnog-upravljanja-2', entity_type: 'cjelozivotni_program', entity_name: 'Voditelj/ica nadzora i korporativnog upravljanja' },
  { url: 'https://effectus.com.hr/osnove-financijske-pismenosti-i-savjetovanje-potrosaca-u-riziku-prezaduzenosti', entity_type: 'cjelozivotni_program', entity_name: 'Osnove financijske pismenosti' },
  { url: 'https://effectus.com.hr/pravo-i-upravljanje-nekretninama',            entity_type: 'cjelozivotni_program', entity_name: 'Pravo i upravljanje nekretninama' },
  { url: 'https://effectus.com.hr/voditelj-ica-uskladenosti-poslovanja-compliance', entity_type: 'cjelozivotni_program', entity_name: 'Voditelj/ica usklađenosti poslovanja' },
  { url: 'https://effectus.com.hr/voditelj-ica-nadzora-i-korporativnog-upravljanja', entity_type: 'cjelozivotni_program', entity_name: 'Voditelj/ica nadzora i korporativnog upravljanja (alt)' },
  { url: 'https://effectus.com.hr/voditelj-ica-ljudskih-potencijala',           entity_type: 'cjelozivotni_program', entity_name: 'Voditelj/ica ljudskih potencijala' },
  { url: 'https://effectus.com.hr/koordinator-ica-u-komunalnim-organizacijama', entity_type: 'cjelozivotni_program', entity_name: 'Koordinator/ica u komunalnim organizacijama' },
  { url: 'https://effectus.com.hr/engleski-poslovni-jezik',                     entity_type: 'cjelozivotni_program', entity_name: 'Engleski poslovni jezik' },
  { url: 'https://effectus.com.hr/kreativno-i-kriticko-misljenje',              entity_type: 'cjelozivotni_program', entity_name: 'Kreativno i kritičko mišljenje' },

  // ─── PREDMETI — BIHEVIORALNA EKONOMIJA ───────────────────────────────────
  { url: 'https://effectus.com.hr/bihevioralna-ekonomija/statisticke-metode-za-bihevioralne-znanosti', entity_type: 'kolegij', entity_name: 'Statističke metode za bihevioralne znanosti' },
  { url: 'https://effectus.com.hr/bihevioralna-ekonomija/bihevioralne-javne-politike',                 entity_type: 'kolegij', entity_name: 'Bihevioralne javne politike' },
  { url: 'https://effectus.com.hr/bihevioralna-ekonomija/bihevioralne-financije',                      entity_type: 'kolegij', entity_name: 'Bihevioralne financije' },
  { url: 'https://effectus.com.hr/bihevioralna-ekonomija/europske-perspektive-bihevioralnog-prava-i-ekonomije', entity_type: 'kolegij', entity_name: 'Europske perspektive bihevioralnog prava i ekonomije' },
  { url: 'https://effectus.com.hr/bihevioralna-ekonomija/bihevioralni-marketing',                      entity_type: 'kolegij', entity_name: 'Bihevioralni marketing' },
  { url: 'https://effectus.com.hr/bihevioralna-ekonomija/socijalna-fizika',                            entity_type: 'kolegij', entity_name: 'Socijalna fizika' },
  { url: 'https://effectus.com.hr/bihevioralna-ekonomija/bihevioralna-teorija-igara',                  entity_type: 'kolegij', entity_name: 'Bihevioralna teorija igara' },
  { url: 'https://effectus.com.hr/bihevioralna-ekonomija/primijenjena-ekonometrija-praktikum',         entity_type: 'kolegij', entity_name: 'Primijenjena ekonometrija – praktikum' },
  { url: 'https://effectus.com.hr/bihevioralna-ekonomija/odlucivanje-u-uvjetima-rizika-i-nesigurnosti', entity_type: 'kolegij', entity_name: 'Odlučivanje u uvjetima rizika i nesigurnosti' },
  { url: 'https://effectus.com.hr/bihevioralna-ekonomija/socijalna-psihologija-ekonomija-2',           entity_type: 'kolegij', entity_name: 'Socijalna psihologija i ekonomija' },
  { url: 'https://effectus.com.hr/bihevioralna-ekonomija/neuroekonomija',                              entity_type: 'kolegij', entity_name: 'Neuroekonomija' },
  { url: 'https://effectus.com.hr/bihevioralna-ekonomija/psihologijaodlucivanjapraktikum',             entity_type: 'kolegij', entity_name: 'Psihologija odlučivanja – praktikum' },

  // ─── PREDMETI — ANALITIČKI MENADŽMENT ────────────────────────────────────
  { url: 'https://effectus.com.hr/analiticki-menadzment/kreativnost-u-digitalnom-dobu',                entity_type: 'kolegij', entity_name: 'Kreativnost u digitalnom dobu' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/komunikacijske-i-prezentacijske-vjestine',     entity_type: 'kolegij', entity_name: 'Komunikacijske i prezentacijske vještine' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/analiza-socijalnih-mreza',                     entity_type: 'kolegij', entity_name: 'Analiza socijalnih mreža' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/primjena-analitickog-menadzmenta',             entity_type: 'kolegij', entity_name: 'Primjena analitičkog menadžmenta – praktikum' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/menadzment-znanja-i-inovacija',                entity_type: 'kolegij', entity_name: 'Menadžment znanja i inovacija' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/kriticko-misljenje',                           entity_type: 'kolegij', entity_name: 'Kritičko mišljenje' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/analiticki-menadzment-2-tehnike-rjesavanja-problema-i-odlucivanja', entity_type: 'kolegij', entity_name: 'Analitički menadžment 2 – Tehnike rješavanja problema' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/psihologija-kreativnosti',                     entity_type: 'kolegij', entity_name: 'Psihologija kreativnosti' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/analiticki-menadzment-1-tehnike-kreativnog-misljenja-2', entity_type: 'kolegij', entity_name: 'Analitički menadžment 1 – Tehnike kreativnog mišljenja' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/upravljanje-promjenama',                       entity_type: 'kolegij', entity_name: 'Upravljanje promjenama' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/pravo-zastite-trzisnog-natjecanja',            entity_type: 'kolegij', entity_name: 'Pravo zaštite tržišnog natjecanja' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/menadzerski-ugovori',                          entity_type: 'kolegij', entity_name: 'Menadžerski ugovori' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/lobiranje',                                    entity_type: 'kolegij', entity_name: 'Lobiranje' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/informacijski-sustavi-za-poslovno-upravljanje', entity_type: 'kolegij', entity_name: 'Informacijski sustavi za poslovno upravljanje' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/analiticki-menadzment-1-tehnike-kreativnog-misljenja', entity_type: 'kolegij', entity_name: 'Analitički menadžment 1 – tehnike kreativnog mišljenja (alt)' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/alternativne-metode-rjesavanja-sporova',       entity_type: 'kolegij', entity_name: 'Alternativne metode rješavanja sporova' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/upravljanje-projektom',                        entity_type: 'kolegij', entity_name: 'Upravljanje projektom' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/upravljanje-ljudskim-potencijalima',           entity_type: 'kolegij', entity_name: 'Upravljanje ljudskim potencijalima' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/teorija-igara',                                entity_type: 'kolegij', entity_name: 'Teorija igara' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/metodologija-znanstveno-istrazivackog-rada',   entity_type: 'kolegij', entity_name: 'Metodologija znanstveno istraživačkog rada' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/krizni-menadzment',                            entity_type: 'kolegij', entity_name: 'Krizni menadžment' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/upravljanje-drustvima-kapitala',               entity_type: 'kolegij', entity_name: 'Upravljanje društvima kapitala' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/strategijski-menadzment',                      entity_type: 'kolegij', entity_name: 'Strategijski menadžment' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/marketinsko-upravljanje-i-primjena',           entity_type: 'kolegij', entity_name: 'Marketinško upravljanje i primjena' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/analiza-financijskih-izvjestaja',              entity_type: 'kolegij', entity_name: 'Analiza financijskih izvještaja' },
  { url: 'https://effectus.com.hr/analiticki-menadzment/specijalisticki-diplomski-rad',                entity_type: 'kolegij', entity_name: 'Specijalistički diplomski rad (Analitički menadžment)' },

  // ─── PREDMETI — FINANCIJE I POSLOVNO PRAVO ───────────────────────────────
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/poslovna-analiza',                        entity_type: 'kolegij', entity_name: 'Poslovna analiza' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/stvarno-pravo',                           entity_type: 'kolegij', entity_name: 'Stvarno pravo' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/racunovodstvo-financijskih-institucija',  entity_type: 'kolegij', entity_name: 'Računovodstvo financijskih institucija' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/pregovaracke-vjestine',                   entity_type: 'kolegij', entity_name: 'Pregovaračke vještine' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/etika-u-poslovanju-i-upravljanju',        entity_type: 'kolegij', entity_name: 'Etika u poslovanju i upravljanju' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/ekonomska-analiza-prava',                 entity_type: 'kolegij', entity_name: 'Ekonomska analiza prava' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/suvremene-financijske-tehnologije',       entity_type: 'kolegij', entity_name: 'Suvremene financijske tehnologije' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/proracunsko-racunovodstvo',               entity_type: 'kolegij', entity_name: 'Proračunsko računovodstvo' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/poslovni-engleski-jezik-3',               entity_type: 'kolegij', entity_name: 'Poslovni engleski jezik 3' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/poslovanje-javnog-sektora',               entity_type: 'kolegij', entity_name: 'Poslovanje javnog sektora' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/zavrsni-rad',                             entity_type: 'kolegij', entity_name: 'Završni rad (Financije i poslovno pravo)' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/poslovne-financije',                      entity_type: 'kolegij', entity_name: 'Poslovne financije' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/osnove-trgovackog-prava',                 entity_type: 'kolegij', entity_name: 'Osnove trgovačkog prava' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/banke-i-bankarsko-poslovanje',            entity_type: 'kolegij', entity_name: 'Banke i bankarsko poslovanje' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/upravni-postupak-i-upravni-spor',         entity_type: 'kolegij', entity_name: 'Upravni postupak i upravni spor' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/pravo-drustava',                          entity_type: 'kolegij', entity_name: 'Pravo društava' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/osiguranja-i-osiguravateljni-rizici',     entity_type: 'kolegij', entity_name: 'Osiguranja i osiguravateljni rizici' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/ekonomika-i-analiza-poslovanja',          entity_type: 'kolegij', entity_name: 'Ekonomika i analiza poslovanja' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/strucna-praksa',                          entity_type: 'kolegij', entity_name: 'Stručna praksa' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/poslovno-planiranje',                     entity_type: 'kolegij', entity_name: 'Poslovno planiranje' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/obvezno-pravo',                           entity_type: 'kolegij', entity_name: 'Obvezno pravo' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/financijsko-racunovodstvo',               entity_type: 'kolegij', entity_name: 'Financijsko računovodstvo' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/poslovni-engleski-jezik-2',               entity_type: 'kolegij', entity_name: 'Poslovni engleski jezik 2' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/osnove-gradanskog-prava',                 entity_type: 'kolegij', entity_name: 'Osnove građanskog prava' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/javne-financije',                         entity_type: 'kolegij', entity_name: 'Javne financije' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/financijska-trzista',                     entity_type: 'kolegij', entity_name: 'Financijska tržišta' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/temeljne-funkcije-upravljanja',           entity_type: 'kolegij', entity_name: 'Temeljne funkcije upravljanja' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/poslovni-engleski-jezik-1',               entity_type: 'kolegij', entity_name: 'Poslovni engleski jezik 1' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/osnove-informatike',                      entity_type: 'kolegij', entity_name: 'Osnove informatike' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/financijska-matematika',                  entity_type: 'kolegij', entity_name: 'Financijska matematika' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/uvod-u-pravo-i-pravosudni-sustav-rh',     entity_type: 'kolegij', entity_name: 'Uvod u pravo i pravosudni sustav RH' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/pocela-ekonomije',                        entity_type: 'kolegij', entity_name: 'Počela ekonomije' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/osnove-racunovodstva',                    entity_type: 'kolegij', entity_name: 'Osnove računovodstva' },
  { url: 'https://effectus.com.hr/financije-i-poslovno-pravo/osnove-matematike',                       entity_type: 'kolegij', entity_name: 'Osnove matematike' },

  // ─── PREDMETI — POREZI I POSLOVNO PRAVO ──────────────────────────────────
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/upravljanje-promjenama',                     entity_type: 'kolegij', entity_name: 'Upravljanje promjenama (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/pravo-zastite-trzisnog-natjecanja',          entity_type: 'kolegij', entity_name: 'Pravo zaštite tržišnog natjecanja (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/menadzerski-ugovori',                        entity_type: 'kolegij', entity_name: 'Menadžerski ugovori (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/lobiranje',                                  entity_type: 'kolegij', entity_name: 'Lobiranje (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/informacijski-sustavi-za-poslovno-upravljanje', entity_type: 'kolegij', entity_name: 'Informacijski sustavi za poslovno upravljanje (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/alternativne-metode-rjesavanja-sporova',     entity_type: 'kolegij', entity_name: 'Alternativne metode rješavanja sporova (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/statusne-promjene-trgovackih-drustava',      entity_type: 'kolegij', entity_name: 'Statusne promjene trgovačkih društava' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/porezno-pravo-i-porezni-postupak',           entity_type: 'kolegij', entity_name: 'Porezno pravo i porezni postupak' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/gospodarsko-kazneno-pravo',                  entity_type: 'kolegij', entity_name: 'Gospodarsko kazneno pravo' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/pravni-okvir-financijskih-institucija',      entity_type: 'kolegij', entity_name: 'Pravni okvir financijskih institucija' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/porezni-sustav-i-primjena-u-republici-hrvatskoj', entity_type: 'kolegij', entity_name: 'Porezni sustav i primjena u RH' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/ovrsno-pravo',                               entity_type: 'kolegij', entity_name: 'Ovršno pravo' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/odstetno-pravo',                             entity_type: 'kolegij', entity_name: 'Odštetno pravo' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/upravljanje-projektom',                      entity_type: 'kolegij', entity_name: 'Upravljanje projektom (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/upravljanje-ljudskim-potencijalima',         entity_type: 'kolegij', entity_name: 'Upravljanje ljudskim potencijalima (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/teorija-igara',                              entity_type: 'kolegij', entity_name: 'Teorija igara (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/krizni-menadzment',                          entity_type: 'kolegij', entity_name: 'Krizni menadžment (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/upravljanje-drustvima-kapitala',             entity_type: 'kolegij', entity_name: 'Upravljanje društvima kapitala (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/strategijski-menadzment',                    entity_type: 'kolegij', entity_name: 'Strategijski menadžment (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/marketinsko-upravljanje-i-primjena',         entity_type: 'kolegij', entity_name: 'Marketinško upravljanje i primjena (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/analiza-financijskih-izvjestaja',            entity_type: 'kolegij', entity_name: 'Analiza financijskih izvještaja (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/specijalisticki-diplomski-rad',              entity_type: 'kolegij', entity_name: 'Specijalistički diplomski rad (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/metodologija-znanstveno-istrazivackog-rada', entity_type: 'kolegij', entity_name: 'Metodologija znanstveno istraživačkog rada (Porezi)' },
  { url: 'https://effectus.com.hr/porezi-i-poslovno-pravo/analiticki-menadzment-1-tehnike-kreativnog-misljenja', entity_type: 'kolegij', entity_name: 'Analitički menadžment 1 – tehnike kreativnog mišljenja (Porezi)' },

  // ─── PREDMETI — MENADŽMENT FINANCIJA ─────────────────────────────────────
  { url: 'https://effectus.com.hr/menadzment-financija/upravljanje-promjenama',                        entity_type: 'kolegij', entity_name: 'Upravljanje promjenama (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/pravo-zastite-trzisnog-natjecanja',             entity_type: 'kolegij', entity_name: 'Pravo zaštite tržišnog natjecanja (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/menadzerski-ugovori',                           entity_type: 'kolegij', entity_name: 'Menadžerski ugovori (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/lobiranje',                                     entity_type: 'kolegij', entity_name: 'Lobiranje (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/informacijski-sustavi-za-poslovno-upravljanje', entity_type: 'kolegij', entity_name: 'Informacijski sustavi za poslovno upravljanje (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/alternativne-metode-rjesavanja-sporova',        entity_type: 'kolegij', entity_name: 'Alternativne metode rješavanja sporova (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/revizija',                                      entity_type: 'kolegij', entity_name: 'Revizija' },
  { url: 'https://effectus.com.hr/menadzment-financija/monetarno-kreditna-analiza',                    entity_type: 'kolegij', entity_name: 'Monetarno kreditna analiza' },
  { url: 'https://effectus.com.hr/menadzment-financija/kontroling',                                    entity_type: 'kolegij', entity_name: 'Kontroling' },
  { url: 'https://effectus.com.hr/menadzment-financija/porezni-sustav-i-primjena-u-republici-hrvatskoj', entity_type: 'kolegij', entity_name: 'Porezni sustav i primjena u RH – praktikum' },
  { url: 'https://effectus.com.hr/menadzment-financija/menadzment-banaka',                             entity_type: 'kolegij', entity_name: 'Menadžment banaka' },
  { url: 'https://effectus.com.hr/menadzment-financija/izrada-investicijskog-projekta',                entity_type: 'kolegij', entity_name: 'Izrada investicijskog projekta – praktikum' },
  { url: 'https://effectus.com.hr/menadzment-financija/financijski-instrumenti-i-instrumenti-osiguranja-rizika', entity_type: 'kolegij', entity_name: 'Financijski instrumenti i instrumenti osiguranja rizika' },
  { url: 'https://effectus.com.hr/menadzment-financija/upravljanje-projektom',                         entity_type: 'kolegij', entity_name: 'Upravljanje projektom (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/upravljanje-ljudskim-potencijalima',            entity_type: 'kolegij', entity_name: 'Upravljanje ljudskim potencijalima (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/teorija-igara',                                 entity_type: 'kolegij', entity_name: 'Teorija igara (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/krizni-menadzment',                             entity_type: 'kolegij', entity_name: 'Krizni menadžment (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/upravljanje-drustvima-kapitala',                entity_type: 'kolegij', entity_name: 'Upravljanje društvima kapitala (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/strategijski-menadzment',                       entity_type: 'kolegij', entity_name: 'Strategijski menadžment (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/marketinsko-upravljanje-i-primjena',            entity_type: 'kolegij', entity_name: 'Marketinško upravljanje i primjena (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/analiza-financijskih-izvjestaja',               entity_type: 'kolegij', entity_name: 'Analiza financijskih izvještaja (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/specijalisticki-diplomski-rad',                 entity_type: 'kolegij', entity_name: 'Specijalistički diplomski rad (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/metodologija-znanstveno-istrazivackog-rada',    entity_type: 'kolegij', entity_name: 'Metodologija znanstveno istraživačkog rada (Men. fin.)' },
  { url: 'https://effectus.com.hr/menadzment-financija/analiticki-menadzment-1-tehnike-kreativnog-misljenja', entity_type: 'kolegij', entity_name: 'Analitički menadžment 1 – tehnike kreativnog mišljenja (Men. fin.)' },

  // ─── PREDMETI — MENADŽMENT LJUDSKIH POTENCIJALA ──────────────────────────
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/menadzment-znanja-i-inovacija-2', entity_type: 'kolegij', entity_name: 'Menadžment znanja i inovacija 2' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/upravljanje-promjenama',    entity_type: 'kolegij', entity_name: 'Upravljanje promjenama (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/pravo-zastite-trzisnog-natjecanja', entity_type: 'kolegij', entity_name: 'Pravo zaštite tržišnog natjecanja (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/menadzerski-ugovori',       entity_type: 'kolegij', entity_name: 'Menadžerski ugovori (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/lobiranje',                 entity_type: 'kolegij', entity_name: 'Lobiranje (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/informacijski-sustavi-za-poslovno-upravljanje', entity_type: 'kolegij', entity_name: 'Informacijski sustavi za poslovno upravljanje (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/alternativne-metode-rjesavanja-sporova', entity_type: 'kolegij', entity_name: 'Alternativne metode rješavanja sporova (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/specijalisticki-diplomski-rad', entity_type: 'kolegij', entity_name: 'Specijalistički diplomski rad (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/psihologija-osobnosti-i-organizacije', entity_type: 'kolegij', entity_name: 'Psihologija osobnosti i organizacije' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/praktikum-u-ljudskim-potencijalima', entity_type: 'kolegij', entity_name: 'Praktikum u ljudskim potencijalima' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/menadzment-znanja-i-inovacija', entity_type: 'kolegij', entity_name: 'Menadžment znanja i inovacija (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/trziste-rada-i-zaposljavanje', entity_type: 'kolegij', entity_name: 'Tržište rada i zapošljavanje' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/tehnike-i-vjestine-vodenja', entity_type: 'kolegij', entity_name: 'Tehnike i vještine vođenja' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/organizacijsko-ponasanje',  entity_type: 'kolegij', entity_name: 'Organizacijsko ponašanje' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/karijera-i-organizacija',  entity_type: 'kolegij', entity_name: 'Karijera i organizacija' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/upravljanje-projektom',    entity_type: 'kolegij', entity_name: 'Upravljanje projektom (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/upravljanje-ljudskim-potencijalima', entity_type: 'kolegij', entity_name: 'Upravljanje ljudskim potencijalima (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/teorija-igara',            entity_type: 'kolegij', entity_name: 'Teorija igara (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/krizni-menadzment',        entity_type: 'kolegij', entity_name: 'Krizni menadžment (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/upravljanje-drustvima-kapitala', entity_type: 'kolegij', entity_name: 'Upravljanje društvima kapitala (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/strategijski-menadzment',  entity_type: 'kolegij', entity_name: 'Strategijski menadžment (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/marketinsko-upravljanje-i-primjena', entity_type: 'kolegij', entity_name: 'Marketinško upravljanje i primjena (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/analiza-financijskih-izvjestaja', entity_type: 'kolegij', entity_name: 'Analiza financijskih izvještaja (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/metodologija-znanstveno-istrazivackog-rada', entity_type: 'kolegij', entity_name: 'Metodologija znanstveno istraživačkog rada (LJP)' },
  { url: 'https://effectus.com.hr/menadzment-ljudskih-potencijala-i-znanja/analiticki-menadzment-1-tehnike-kreativnog-misljenja', entity_type: 'kolegij', entity_name: 'Analitički menadžment 1 (LJP)' },

  // ─── PREDMETI — STANDALONE ────────────────────────────────────────────────
  { url: 'https://effectus.com.hr/pravo-drustava',                              entity_type: 'kolegij', entity_name: 'Pravo društava' },
  { url: 'https://effectus.com.hr/radno-pravo',                                 entity_type: 'kolegij', entity_name: 'Radno pravo' },
  { url: 'https://effectus.com.hr/trgovacko-ugovorno-pravo',                    entity_type: 'kolegij', entity_name: 'Trgovačko ugovorno pravo' },
  { url: 'https://effectus.com.hr/javna-nabava',                                entity_type: 'kolegij', entity_name: 'Javna nabava' },
  { url: 'https://effectus.com.hr/pravo-osiguranja',                            entity_type: 'kolegij', entity_name: 'Pravo osiguranja' },
  { url: 'https://effectus.com.hr/poduzetnistvo-i-inovacije',                   entity_type: 'kolegij', entity_name: 'Poduzetništvo i inovacije' },
  { url: 'https://effectus.com.hr/uvod-u-ekonomiju',                            entity_type: 'kolegij', entity_name: 'Uvod u ekonomiju' },
  { url: 'https://effectus.com.hr/osnove-statistike',                           entity_type: 'kolegij', entity_name: 'Osnove statistike' },
  { url: 'https://effectus.com.hr/predmeti/digitalna-ekonomija-i-poduzetnistvo', entity_type: 'kolegij', entity_name: 'Digitalna ekonomija i poduzetništvo' },

  // ─── KONTAKT ──────────────────────────────────────────────────────────────
  { url: 'https://effectus.com.hr/kontakt',                                     entity_type: 'opcenito', entity_name: 'Kontakt' },
];

// Pages to SKIP
export const SKIP_PATTERNS = [
  /\/en\b/,                    // English content
  /\/politika-privatnosti/,    // Privacy policy
  /\/izjava-o-zastiti/,        // Data protection
  /\/novosti\//,               // News items (dynamic)
  /\/media\//,                 // Media files
  /\/wp-admin\//,              // WordPress admin
  /\/wp-json\//,               // WP API
  /\/page\//,                  // Pagination
  /\?/,                        // Query strings
  /\.pdf$/,                    // PDFs
];
